filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies: { override: true }
  nodes:
    analysis: # see https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
      project_setup: { override: true }
      tests: { override: true }

tools:
  external_code_coverage: true
