filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit tests/Unit/ --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
