language: php

# php compatibility
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

matrix:
  allow_failures:
    - php: '7.4snapshot'

# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry bash develop/install-development-tools

script:
  - tools/php-cs-fixer fix --verbose
  - tools/phpcbf --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - tools/phpstan analyse --level max --no-progress --verbose src/ tests/
  - tools/psalm --no-progress
  - phpdbg -qrr tools/infection --show-mutations || true

notifications:
  email: false
